language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
script: npm test
deploy:
  provider: npm
  email: mugo@forfuture.co.ke
  api_key:
    secure: AJEpXQ+muyGhjr++vVDR5YDd+d7rtijcD/nQo5FbwAbG90kEKJOAWIJBy+rn6vgjyJKWkUxCyjD8Th7wlDqDsYjdi0mgiNV7HbVHbQnSzGDvQkzx/OKrFChfLWK/eSZG/KUe9vNQaxzr1a6tEgyZfVOa1WvmwfSP44essMqCqzw=
  on:
    tags: true
    repo: GochoMugo/node-show-deps
